"""SQL Validators - Validate SQL queries against schema

This module provides utilities for validating SQL queries, particularly
those generated by LLMs, to prevent execution of invalid queries.
"""

from __future__ import annotations

import re
import sqlite3
from dataclasses import dataclass
from typing import Set

try:
    import sqlparse

    HAS_SQLPARSE = True
except ImportError:
    HAS_SQLPARSE = False


@dataclass
class ValidationResult:
    """Result of SQL validation."""

    valid: bool
    errors: list[str]
    warnings: list[str]
    missing_columns: Set[str] = None

    def __post_init__(self):
        """Initialize missing_columns if not provided."""
        if self.missing_columns is None:
            self.missing_columns = set()


class SQLValidator:
    """
    Validate SQL queries against schema metadata.

    This validator ensures that LLM-generated SQL queries reference only
    valid columns and tables before execution. This prevents hallucination
    errors where the LLM invents column names.

    Features:
    - Column validation against schema
    - Column extraction from SQL
    - Table validation
    - Clear error messages for debugging

    Example:
        schema_columns = {"id", "name", "email", "created_at"}

        sql = "SELECT name, email FROM users WHERE created_at > '2023-01-01'"
        result = SQLValidator.validate_columns(sql, schema_columns)

        if not result.valid:
            print(f"Invalid columns: {result.missing_columns}")
    """

    @staticmethod
    def validate_columns(
        sql: str,
        schema_columns: Set[str],
        strict: bool = False,
    ) -> ValidationResult:
        """
        Validate that all columns referenced in SQL exist in schema.

        Args:
            sql: SQL query string
            schema_columns: Set of valid column names
            strict: If True, fail on any unrecognized identifier (default: False)
                   If False, allow common SQL keywords and functions

        Returns:
            ValidationResult with validation status and details

        Example:
            >>> schema = {"id", "name", "age"}
            >>> sql = "SELECT name, age FROM users"
            >>> result = SQLValidator.validate_columns(sql, schema)
            >>> assert result.valid

            >>> bad_sql = "SELECT name, invalid_col FROM users"
            >>> result = SQLValidator.validate_columns(bad_sql, schema)
            >>> assert not result.valid
            >>> assert "invalid_col" in result.missing_columns
        """
        errors = []
        warnings = []
        missing_columns: Set[str] = set()

        # Extract all referenced columns
        try:
            referenced_columns = SQLValidator.extract_columns(sql)
        except (ValueError, TypeError, re.error) as e:
            return ValidationResult(
                valid=False, errors=[f"Failed to parse SQL: {e}"], warnings=[]
            )

        # Normalize schema columns to lowercase for comparison
        schema_lower = {col.lower() for col in schema_columns}

        # Check each referenced column
        for col in referenced_columns:
            col_lower = col.lower()

            # Skip common SQL keywords and functions
            if SQLValidator._is_sql_keyword(col_lower):
                continue

            # Check if column exists
            if col_lower not in schema_lower:
                missing_columns.add(col)
                if strict:
                    errors.append(
                        f"Column '{col}' not found in schema. "
                        f"Available: {', '.join(sorted(schema_columns))}"
                    )

        if errors:
            return ValidationResult(
                valid=False, errors=errors, warnings=warnings, missing_columns=missing_columns
            )

        if missing_columns and not strict:
            warnings.append(
                f"Potentially invalid columns: {', '.join(sorted(missing_columns))}. "
                f"These may be valid if they're from subqueries or derived tables."
            )

        valid = len(errors) == 0

        return ValidationResult(
            valid=valid, errors=errors, warnings=warnings, missing_columns=missing_columns
        )

    @staticmethod
    def extract_columns(sql: str) -> Set[str]:
        """
        Extract column names referenced in SQL query.

        This is the same logic as in metadata_helpers but focused on
        column extraction for validation purposes.

        Args:
            sql: SQL query string

        Returns:
            Set of column names

        Example:
            >>> sql = "SELECT id, name FROM users WHERE age > 18"
            >>> cols = SQLValidator.extract_columns(sql)
            >>> assert cols >= {"id", "name", "age"}
        """
        columns: Set[str] = set()

        # Normalize SQL
        sql_normalized = sql.replace("\n", " ").replace("\t", " ")

        # Pattern 1: SELECT clause
        select_pattern = r"SELECT\s+(?:DISTINCT\s+)?(.+?)(?:FROM|WHERE|GROUP|ORDER|LIMIT|;|$)"
        select_match = re.search(select_pattern, sql_normalized, re.IGNORECASE)
        if select_match:
            select_clause = select_match.group(1)
            for col in select_clause.split(","):
                col = col.strip()
                # Remove aliases
                col = re.sub(r"\s+AS\s+\w+", "", col, flags=re.IGNORECASE)
                # Handle table.column notation
                if "." in col:
                    col = col.split(".")[-1]
                # Handle functions
                col = re.sub(r"\w+\s*\((.+?)\)", r"\1", col)
                # Clean up
                col = col.strip().replace("`", "").replace('"', "")
                if col and col != "*":
                    columns.add(col.lower())

        # Pattern 2: WHERE, HAVING clauses
        condition_pattern = r"(?:WHERE|HAVING)\s+(.+?)(?:GROUP|ORDER|LIMIT|;|$)"
        for match in re.finditer(condition_pattern, sql_normalized, re.IGNORECASE):
            condition = match.group(1)
            condition_no_quotes = re.sub(r"'[^']*'|\"[^\"]*\"", "", condition)
            col_matches = re.findall(
                r"\b([a-zA-Z_]\w*)\s*(?:=|<|>|!=|LIKE|IN|BETWEEN|NOT)",
                condition_no_quotes,
                re.IGNORECASE,
            )
            for col in col_matches:
                if col.lower() not in ("and", "or", "not"):
                    columns.add(col.lower())

        # Pattern 3: ORDER BY, GROUP BY
        order_group_pattern = r"(?:ORDER\s+BY|GROUP\s+BY)\s+(.+?)(?:ORDER|GROUP|LIMIT|;|$)"
        for match in re.finditer(order_group_pattern, sql_normalized, re.IGNORECASE):
            cols_str = match.group(1)
            for col_expr in cols_str.split(","):
                col_expr = col_expr.strip()
                col_expr = re.sub(r"\s+(?:ASC|DESC)$", "", col_expr, flags=re.IGNORECASE)
                id_match = re.match(r"(?:`|\")?([a-zA-Z_]\w*)(?:`|\")?", col_expr)
                if id_match:
                    col = id_match.group(1)
                    columns.add(col.lower())

        # Pattern 4: ON clause (joins)
        on_pattern = r"ON\s+(.+?)(?:WHERE|GROUP|ORDER|LIMIT|INNER|LEFT|RIGHT|FULL|;|$)"
        for match in re.finditer(on_pattern, sql_normalized, re.IGNORECASE):
            condition = match.group(1)
            condition_no_quotes = re.sub(r"'[^']*'|\"[^\"]*\"", "", condition)
            col_matches = re.findall(
                r"\b([a-zA-Z_]\w*)\s*(?:=|<|>|!=)", condition_no_quotes, re.IGNORECASE
            )
            for col in col_matches:
                if col.lower() not in ("and", "or"):
                    columns.add(col.lower())

        return columns

    @staticmethod
    def _is_sql_keyword(word: str) -> bool:
        """
        Check if a word is a SQL keyword or function.

        Args:
            word: Word to check

        Returns:
            True if word is likely a SQL keyword or function
        """
        sql_keywords = {
            # Keywords
            "select",
            "from",
            "where",
            "and",
            "or",
            "not",
            "in",
            "like",
            "is",
            "null",
            "true",
            "false",
            "case",
            "when",
            "then",
            "else",
            "end",
            "having",
            "group",
            "order",
            "by",
            "asc",
            "desc",
            "limit",
            "offset",
            "distinct",
            "all",
            "any",
            "some",
            "between",
            "exists",
            "union",
            "except",
            "intersect",
            # Common functions
            "count",
            "sum",
            "avg",
            "max",
            "min",
            "abs",
            "round",
            "length",
            "substring",
            "upper",
            "lower",
            "trim",
            "coalesce",
            "cast",
            "date",
            "year",
            "month",
            "day",
            "now",
            "current_date",
            # Aggregate functions
            "stddev",
            "variance",
            "collect",
            "listagg",
            # Window functions
            "row_number",
            "rank",
            "dense_rank",
            "lag",
            "lead",
        }
        return word.lower() in sql_keywords

    @staticmethod
    def validate_tables(
        sql: str,
        valid_tables: Set[str],
    ) -> ValidationResult:
        """
        Validate that all tables referenced in SQL exist.

        Args:
            sql: SQL query string
            valid_tables: Set of valid table names

        Returns:
            ValidationResult with validation status

        Example:
            >>> tables = {"users", "orders"}
            >>> sql = "SELECT * FROM users u JOIN orders o ON u.id = o.user_id"
            >>> result = SQLValidator.validate_tables(sql, tables)
            >>> assert result.valid
        """
        errors = []
        referenced_tables: Set[str] = set()

        # Extract tables from FROM and JOIN clauses
        sql_normalized = sql.replace("\n", " ").replace("\t", " ")

        # Pattern for FROM clause
        from_pattern = r"FROM\s+([a-zA-Z_]\w*)"
        for match in re.finditer(from_pattern, sql_normalized, re.IGNORECASE):
            table = match.group(1).lower()
            referenced_tables.add(table)

        # Pattern for JOIN clauses
        join_pattern = r"(?:INNER|LEFT|RIGHT|FULL)?\s*JOIN\s+([a-zA-Z_]\w*)"
        for match in re.finditer(join_pattern, sql_normalized, re.IGNORECASE):
            table = match.group(1).lower()
            referenced_tables.add(table)

        # Validate each table
        valid_tables_lower = {t.lower() for t in valid_tables}

        for table in referenced_tables:
            if table not in valid_tables_lower:
                errors.append(
                    f"Table '{table}' not found. "
                    f"Available tables: {', '.join(sorted(valid_tables))}"
                )

        return ValidationResult(
            valid=len(errors) == 0,
            errors=errors,
            warnings=[],
        )

    @staticmethod
    def validate_syntax(sql: str, use_parser: bool = True) -> ValidationResult:
        """
        Perform SQL syntax validation using sqlparse library.

        This validates that the SQL is parseable and checks for common
        syntax errors. Uses sqlparse if available, falls back to basic checks.

        Args:
            sql: SQL query string
            use_parser: Whether to use sqlparse for parsing (default: True)

        Returns:
            ValidationResult with syntax validation status

        Example:
            >>> sql = "SELECT name FROM users WHERE id = 1"
            >>> result = SQLValidator.validate_syntax(sql)
            >>> assert result.valid

            >>> bad_sql = "SELECT name FROM WHERE"
            >>> result = SQLValidator.validate_syntax(bad_sql)
            >>> assert not result.valid
        """
        errors = []
        warnings = []

        sql = sql.strip()

        # Check basic structure
        if not sql:
            errors.append("SQL query is empty")
            return ValidationResult(valid=False, errors=errors, warnings=warnings)

        # Use sqlparse if available and requested
        if use_parser and HAS_SQLPARSE:
            try:
                parsed = sqlparse.parse(sql)

                if not parsed:
                    errors.append("Failed to parse SQL - invalid syntax")
                    return ValidationResult(valid=False, errors=errors, warnings=warnings)

                # Check each statement
                for statement in parsed:
                    # Get tokens and check for obvious errors
                    tokens = [t for t in statement.tokens if not t.is_whitespace]

                    if not tokens:
                        errors.append("Empty SQL statement")
                        continue

                    # Check first token is a valid statement start
                    first_token = str(tokens[0]).upper()
                    valid_starts = [
                        "SELECT",
                        "INSERT",
                        "UPDATE",
                        "DELETE",
                        "WITH",
                        "CREATE",
                        "DROP",
                        "ALTER",
                        "EXPLAIN",
                    ]
                    if first_token not in valid_starts:
                        warnings.append(
                            f"Statement starts with '{first_token}' - "
                            f"expected one of: {', '.join(valid_starts)}"
                        )

                    # Check for common malformed patterns
                    sql_upper = sql.upper()

                    # Check for LIMIT without proper FROM clause
                    if "LIMIT" in sql_upper:
                        # Make sure there's a FROM before LIMIT
                        limit_pos = sql_upper.find("LIMIT")
                        before_limit = sql_upper[:limit_pos]
                        if "FROM" not in before_limit:
                            errors.append("LIMIT clause found without FROM clause")
                        # Check for missing value after LIMIT
                        after_limit = sql_upper[limit_pos:].replace("LIMIT", "", 1).strip()
                        if not after_limit or not after_limit[0].isdigit():
                            errors.append("LIMIT clause requires a numeric value")

                    # Check for consecutive keywords that shouldn't be together
                    bad_pairs = [
                        ("FROM", "WHERE"),
                        ("FROM", "LIMIT"),
                        ("FROM", "ORDER"),
                        ("SELECT", "FROM"),
                        ("WHERE", "FROM"),
                        ("WHERE", "ORDER"),
                    ]
                    for i, token in enumerate(tokens[:-1]):
                        if not token.is_keyword:
                            continue
                        token_str = str(token).upper().strip()
                        next_token = tokens[i + 1]
                        if next_token.is_keyword:
                            next_str = str(next_token).upper().strip()
                            if (token_str, next_str) in bad_pairs:
                                errors.append(
                                    f"Invalid syntax: '{token_str}' followed by '{next_str}'"
                                )

            except (ValueError, TypeError, AttributeError) as e:
                errors.append(f"SQL parsing failed: {e}")
        else:
            # Fallback to basic validation if sqlparse not available
            if not HAS_SQLPARSE and use_parser:
                warnings.append(
                    "sqlparse not installed - using basic validation. "
                    "Install with: pip install sqlparse"
                )

            # Check for unmatched parentheses
            open_count = sql.count("(") - sql.count("\\(")
            close_count = sql.count(")") - sql.count("\\)")
            if open_count != close_count:
                errors.append(f"Unmatched parentheses: {open_count} open, {close_count} close")

            # Check for unmatched quotes
            single_quotes = len(re.findall(r"(?<!\\)'", sql)) % 2
            double_quotes = len(re.findall(r"(?<!\\)\"", sql)) % 2
            if single_quotes != 0:
                errors.append("Unmatched single quotes")
            if double_quotes != 0:
                errors.append("Unmatched double quotes")

            # Check for SELECT/FROM
            if not re.search(r"\bSELECT\b", sql, re.IGNORECASE):
                warnings.append("Query doesn't contain SELECT keyword")
            if not re.search(r"\bFROM\b", sql, re.IGNORECASE):
                warnings.append("Query doesn't contain FROM keyword")

        return ValidationResult(
            valid=len(errors) == 0,
            errors=errors,
            warnings=warnings,
        )

    @staticmethod
    def validate_with_db_dryrun(
        sql: str, db_connection, dialect: str = "sqlite"
    ) -> ValidationResult:
        """
        Validate SQL by doing a database dry-run using EXPLAIN.

        This uses the database engine itself to validate the query
        without actually executing it. This catches syntax errors,
        invalid table/column references, and other runtime issues.

        Args:
            sql: SQL query string
            db_connection: Database connection (e.g., sqlite3.Connection)
            dialect: Database dialect ('sqlite', 'postgres', 'mysql')

        Returns:
            ValidationResult with validation status from database

        Example:
            >>> import sqlite3
            >>> conn = sqlite3.connect(":memory:")
            >>> conn.execute("CREATE TABLE users (id INTEGER, name TEXT)")
            >>> sql = "SELECT name FROM users"
            >>> result = SQLValidator.validate_with_db_dryrun(sql, conn)
            >>> assert result.valid
        """
        errors = []
        warnings = []

        if not sql or not sql.strip():
            return ValidationResult(valid=False, errors=["SQL query is empty"], warnings=[])

        try:
            cursor = db_connection.cursor()

            # Use EXPLAIN to validate without executing
            # This works for SQLite, PostgreSQL, and MySQL
            if dialect == "sqlite":
                # SQLite uses EXPLAIN QUERY PLAN
                cursor.execute(f"EXPLAIN QUERY PLAN {sql}")
            elif dialect == "postgres":
                # PostgreSQL uses EXPLAIN
                cursor.execute(f"EXPLAIN {sql}")
            elif dialect == "mysql":
                # MySQL uses EXPLAIN
                cursor.execute(f"EXPLAIN {sql}")
            else:
                warnings.append(f"Unknown dialect '{dialect}' - trying EXPLAIN anyway")
                cursor.execute(f"EXPLAIN {sql}")

            # If we get here, the query is valid
            cursor.close()

        except sqlite3.OperationalError as e:
            error_msg = str(e)
            errors.append(f"Database validation failed: {error_msg}")

            # Provide helpful hints for common errors
            if "no such table" in error_msg.lower():
                errors.append("Hint: Check that the table name exists in the database")
            elif "no such column" in error_msg.lower():
                errors.append("Hint: Check that column names match the schema exactly")
            elif "syntax error" in error_msg.lower():
                errors.append("Hint: Check SQL syntax - there may be missing/extra keywords")

        except (AttributeError, TypeError, OSError) as e:
            errors.append(f"Database validation error: {e}")

        return ValidationResult(
            valid=len(errors) == 0,
            errors=errors,
            warnings=warnings,
        )
